# CMS Routes Configuration
# Admin routes with authentication

routes:
  # Authentication routes
  login:
    method: GET
    route: /login
    controller: Neuron\Cms\Controllers\Auth\LoginController@showLoginForm

  login_post:
    method: POST
    route: /login
    controller: Neuron\Cms\Controllers\Auth\LoginController@login

  logout:
    method: POST
    route: /logout
    controller: Neuron\Cms\Controllers\Auth\LoginController@logout
    filter: auth

  # Password Reset routes
  forgot_password:
    method: GET
    route: /forgot-password
    controller: Neuron\Cms\Controllers\Auth\PasswordResetController@showForgotPasswordForm

  forgot_password_post:
    method: POST
    route: /forgot-password
    controller: Neuron\Cms\Controllers\Auth\PasswordResetController@requestReset

  reset_password:
    method: GET
    route: /reset-password
    controller: Neuron\Cms\Controllers\Auth\PasswordResetController@showResetForm

  reset_password_post:
    method: POST
    route: /reset-password
    controller: Neuron\Cms\Controllers\Auth\PasswordResetController@resetPassword

  # Admin Dashboard
  admin:
    method: GET
    route: /admin
    controller: Neuron\Cms\Controllers\Admin\DashboardController@index
    filter: auth

  admin_dashboard:
    method: GET
    route: /admin/dashboard
    controller: Neuron\Cms\Controllers\Admin\DashboardController@index
    filter: auth

  # User Management
  admin_users:
    method: GET
    route: /admin/users
    controller: Neuron\Cms\Controllers\Admin\UserController@index
    filter: auth

  admin_users_create:
    method: GET
    route: /admin/users/create
    controller: Neuron\Cms\Controllers\Admin\UserController@create
    filter: auth

  admin_users_store:
    method: POST
    route: /admin/users
    controller: Neuron\Cms\Controllers\Admin\UserController@store
    filter: auth

  admin_users_edit:
    method: GET
    route: /admin/users/:id/edit
    controller: Neuron\Cms\Controllers\Admin\UserController@edit
    filter: auth

  admin_users_update:
    method: PUT
    route: /admin/users/:id
    controller: Neuron\Cms\Controllers\Admin\UserController@update
    filter: auth

  admin_users_destroy:
    method: DELETE
    route: /admin/users/:id
    controller: Neuron\Cms\Controllers\Admin\UserController@destroy
    filter: auth

  # Profile Management
  admin_profile:
    method: GET
    route: /admin/profile
    controller: Neuron\Cms\Controllers\Admin\ProfileController@edit
    filter: auth

  admin_profile_update:
    method: PUT
    route: /admin/profile
    controller: Neuron\Cms\Controllers\Admin\ProfileController@update
    filter: auth

  # Blog Post Management
  admin_posts:
    method: GET
    route: /admin/posts
    controller: Neuron\Cms\Controllers\Admin\PostController@index
    filter: auth

  admin_posts_create:
    method: GET
    route: /admin/posts/create
    controller: Neuron\Cms\Controllers\Admin\PostController@create
    filter: auth

  admin_posts_store:
    method: POST
    route: /admin/posts
    controller: Neuron\Cms\Controllers\Admin\PostController@store
    filter: auth

  admin_posts_edit:
    method: GET
    route: /admin/posts/:id/edit
    controller: Neuron\Cms\Controllers\Admin\PostController@edit
    filter: auth

  admin_posts_update:
    method: PUT
    route: /admin/posts/:id
    controller: Neuron\Cms\Controllers\Admin\PostController@update
    filter: auth

  admin_posts_destroy:
    method: DELETE
    route: /admin/posts/:id
    controller: Neuron\Cms\Controllers\Admin\PostController@destroy
    filter: auth

  # Blog Category Management
  admin_categories:
    method: GET
    route: /admin/categories
    controller: Neuron\Cms\Controllers\Admin\CategoryController@index
    filter: auth

  admin_categories_create:
    method: GET
    route: /admin/categories/create
    controller: Neuron\Cms\Controllers\Admin\CategoryController@create
    filter: auth

  admin_categories_store:
    method: POST
    route: /admin/categories
    controller: Neuron\Cms\Controllers\Admin\CategoryController@store
    filter: auth

  admin_categories_edit:
    method: GET
    route: /admin/categories/:id/edit
    controller: Neuron\Cms\Controllers\Admin\CategoryController@edit
    filter: auth

  admin_categories_update:
    method: PUT
    route: /admin/categories/:id
    controller: Neuron\Cms\Controllers\Admin\CategoryController@update
    filter: auth

  admin_categories_destroy:
    method: DELETE
    route: /admin/categories/:id
    controller: Neuron\Cms\Controllers\Admin\CategoryController@destroy
    filter: auth

  # Blog Tag Management
  admin_tags:
    method: GET
    route: /admin/tags
    controller: Neuron\Cms\Controllers\Admin\TagController@index
    filter: auth

  admin_tags_create:
    method: GET
    route: /admin/tags/create
    controller: Neuron\Cms\Controllers\Admin\TagController@create
    filter: auth

  admin_tags_store:
    method: POST
    route: /admin/tags
    controller: Neuron\Cms\Controllers\Admin\TagController@store
    filter: auth

  admin_tags_edit:
    method: GET
    route: /admin/tags/:id/edit
    controller: Neuron\Cms\Controllers\Admin\TagController@edit
    filter: auth

  admin_tags_update:
    method: PUT
    route: /admin/tags/:id
    controller: Neuron\Cms\Controllers\Admin\TagController@update
    filter: auth

  admin_tags_destroy:
    method: DELETE
    route: /admin/tags/:id
    controller: Neuron\Cms\Controllers\Admin\TagController@destroy
    filter: auth

  # Homepage
  home:
    method: GET
    route: /
    controller: Neuron\Cms\Controllers\Home@index

  # Public Blog Routes
  blog:
    method: GET
    route: /blog
    controller: Neuron\Cms\Controllers\Blog@index

  blog_post:
    method: GET
    route: /blog/post/:slug
    controller: Neuron\Cms\Controllers\Blog@show

  blog_category:
    method: GET
    route: /blog/category/:slug
    controller: Neuron\Cms\Controllers\Blog@category

  blog_tag:
    method: GET
    route: /blog/tag/:slug
    controller: Neuron\Cms\Controllers\Blog@tag

  blog_author:
    method: GET
    route: /blog/author/:username
    controller: Neuron\Cms\Controllers\Blog@author

  rss:
    method: GET
    route: /rss
    controller: Neuron\Cms\Controllers\Blog@feed
