# CMS Routes Configuration
# Admin routes with authentication

routes:
  # Authentication routes
  - method: GET
    route: /login
    controller: Neuron\Cms\Controllers\Auth\LoginController@showLoginForm

  - method: POST
    route: /login
    controller: Neuron\Cms\Controllers\Auth\LoginController@login

  - method: POST
    route: /logout
    controller: Neuron\Cms\Controllers\Auth\LoginController@logout
    filter: auth

  # Password Reset routes
  - method: GET
    route: /forgot-password
    controller: Neuron\Cms\Controllers\Auth\PasswordResetController@showForgotPasswordForm

  - method: POST
    route: /forgot-password
    controller: Neuron\Cms\Controllers\Auth\PasswordResetController@requestReset

  - method: GET
    route: /reset-password
    controller: Neuron\Cms\Controllers\Auth\PasswordResetController@showResetForm

  - method: POST
    route: /reset-password
    controller: Neuron\Cms\Controllers\Auth\PasswordResetController@resetPassword

  # Admin Dashboard
  - method: GET
    route: /admin
    controller: Neuron\Cms\Controllers\Admin\DashboardController@index
    filter: auth

  - method: GET
    route: /admin/dashboard
    controller: Neuron\Cms\Controllers\Admin\DashboardController@index
    filter: auth

  # User Management
  - method: GET
    route: /admin/users
    controller: Neuron\Cms\Controllers\Admin\UserController@index
    filter: auth

  - method: GET
    route: /admin/users/create
    controller: Neuron\Cms\Controllers\Admin\UserController@create
    filter: auth

  - method: POST
    route: /admin/users
    controller: Neuron\Cms\Controllers\Admin\UserController@store
    filter: auth

  - method: GET
    route: /admin/users/:id/edit
    controller: Neuron\Cms\Controllers\Admin\UserController@edit
    filter: auth

  - method: PUT
    route: /admin/users/:id
    controller: Neuron\Cms\Controllers\Admin\UserController@update
    filter: auth

  - method: DELETE
    route: /admin/users/:id
    controller: Neuron\Cms\Controllers\Admin\UserController@destroy
    filter: auth

  # Profile Management
  - method: GET
    route: /admin/profile
    controller: Neuron\Cms\Controllers\Admin\ProfileController@edit
    filter: auth

  - method: PUT
    route: /admin/profile
    controller: Neuron\Cms\Controllers\Admin\ProfileController@update
    filter: auth

  # Blog Post Management
  - method: GET
    route: /admin/posts
    controller: Neuron\Cms\Controllers\Admin\PostController@index
    filter: auth

  - method: GET
    route: /admin/posts/create
    controller: Neuron\Cms\Controllers\Admin\PostController@create
    filter: auth

  - method: POST
    route: /admin/posts
    controller: Neuron\Cms\Controllers\Admin\PostController@store
    filter: auth

  - method: GET
    route: /admin/posts/:id/edit
    controller: Neuron\Cms\Controllers\Admin\PostController@edit
    filter: auth

  - method: PUT
    route: /admin/posts/:id
    controller: Neuron\Cms\Controllers\Admin\PostController@update
    filter: auth

  - method: DELETE
    route: /admin/posts/:id
    controller: Neuron\Cms\Controllers\Admin\PostController@destroy
    filter: auth

  # Blog Category Management
  - method: GET
    route: /admin/categories
    controller: Neuron\Cms\Controllers\Admin\CategoryController@index
    filter: auth

  - method: GET
    route: /admin/categories/create
    controller: Neuron\Cms\Controllers\Admin\CategoryController@create
    filter: auth

  - method: POST
    route: /admin/categories
    controller: Neuron\Cms\Controllers\Admin\CategoryController@store
    filter: auth

  - method: GET
    route: /admin/categories/:id/edit
    controller: Neuron\Cms\Controllers\Admin\CategoryController@edit
    filter: auth

  - method: PUT
    route: /admin/categories/:id
    controller: Neuron\Cms\Controllers\Admin\CategoryController@update
    filter: auth

  - method: DELETE
    route: /admin/categories/:id
    controller: Neuron\Cms\Controllers\Admin\CategoryController@destroy
    filter: auth

  # Blog Tag Management
  - method: GET
    route: /admin/tags
    controller: Neuron\Cms\Controllers\Admin\TagController@index
    filter: auth

  - method: GET
    route: /admin/tags/create
    controller: Neuron\Cms\Controllers\Admin\TagController@create
    filter: auth

  - method: POST
    route: /admin/tags
    controller: Neuron\Cms\Controllers\Admin\TagController@store
    filter: auth

  - method: GET
    route: /admin/tags/:id/edit
    controller: Neuron\Cms\Controllers\Admin\TagController@edit
    filter: auth

  - method: PUT
    route: /admin/tags/:id
    controller: Neuron\Cms\Controllers\Admin\TagController@update
    filter: auth

  - method: DELETE
    route: /admin/tags/:id
    controller: Neuron\Cms\Controllers\Admin\TagController@destroy
    filter: auth

  # Public Blog Routes
  - method: GET
    route: /
    controller: Neuron\Cms\Controllers\Blog@index

  - method: GET
    route: /blog
    controller: Neuron\Cms\Controllers\Blog@index

  - method: GET
    route: /blog/post/:slug
    controller: Neuron\Cms\Controllers\Blog@post

  - method: GET
    route: /blog/category/:slug
    controller: Neuron\Cms\Controllers\Blog@category

  - method: GET
    route: /blog/tag/:slug
    controller: Neuron\Cms\Controllers\Blog@tag

  - method: GET
    route: /blog/author/:username
    controller: Neuron\Cms\Controllers\Blog@author

  - method: GET
    route: /rss
    controller: Neuron\Cms\Controllers\Blog@rss
