dto:
  token:
    type: string
    required: true
    minLength: 64
    maxLength: 64
  password:
    type: string
    required: true
    minLength: 8
    maxLength: 255
  password_confirmation:
    type: string
    required: true
    minLength: 8
    maxLength: 255
